language: python
python: 3.7

install:
    - 'pip install -r requirements.txt'

script:
    - ":"
    
deploy:
    -   provider: pypi
        user: __token__
        password: $PYPI_TOKEN
        distributions: 'sdist bdist_wheel'
        skip_existing: true
